version: "3"

services: 
  valheim: 
    container_name: valheim_server
    image: ghcr.io/lloesche/valheim-server
    cap_add:
      - sys_nice
    volumes: 
      - $HOME/valheim/config:/config
      - $HOME/valheim/data:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - $HOME/valheim/valheim.env
    restart: always
    stop_grace_period: 2m
